version: '3'

services:
  api:
    build: ./api
    container_name: crud-api
    command: node ./dist/app.js
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/api
    depends_on:
      - mongo
    networks:
      - crud_network

  mongo:
    image: mongo:4.4.1-bionic
    container_name: crud-mongo
    ports:
      - '27017:27017'
    networks:
      - crud_network

networks:
  crud_network:
    driver: bridge
