version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: crud-frontend
    command: serve -s build -l 3000
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - crud_network

  api:
    build: ./api
    container_name: crud-api
    command: node ./dist/app.js
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/api
    depends_on:
      - mongo
    networks:
      - crud_network

  mongo:
    image: mongo:4.4.1-bionic
    container_name: crud-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_api:/data/db
    networks:
      - crud_network

volumes:
  mongo_api:

networks:
  crud_network:
    driver: bridge
